volumes:
  cache: {}

networks:
  currencier-net:
    name: currencier-net
    driver: bridge

services:
  currencier:
    container_name: currencier
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - 8080:8080
    networks:
      - currencier-net
    depends_on:
      cache:
        condition: service_healthy

  cache:
    container_name: cache
    image: redis:7.2.4
    restart: always
    ports:
      - 6380:6379
    volumes: 
      - cache:/data
    networks:
      - currencier-net
    healthcheck:
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 2s
      test: ["CMD", "redis-cli","ping"]
    