services:
  currencier:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - 8080:8080
    depends_on:
      cache:
        condition: service_healthy

  cache:
    container_name: cache
    image: redis:7.2.4
    restart: always
    ports:
      - 6380:6379
    volumes: 
      - cache:/data
    healthcheck:
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 2s
      test: ["CMD", "redis-cli","ping"]

volumes:
  cache: {}
